google/trillian-examples

etherslurp/ui/ui.go

I think this is the correct way to do it now. The field it was accessing has been removed.

Fix etherslurp UI for SignedMapRoot format change

---

etherslurp/Makefile
etherslurp/README.md

Fix docs & Makefile to work from clean dirs

---

gossip/client/ct.go
gossip/client/ct_test.go

This makes it easier to log STHs from Certificate Transparency logs.

gossip: add HubClient.AddCTSTH() helper method

---

gossip/hub/instance.go

Some signature algorithms (e.g. Ed25519) do not hash before signing.

gossip: allow hash algorithm of None

---

.travis.yml

Trial using the Google module proxy in travis builds:
- in preparation for [Golang module transparency](https://blog.golang.org/modules2019)
- Make dep fetching faster and more reliable.

Enable golang mod proxy on travis

---

.travis.yml

Ensures that go.mod is committed in a clean and accurate state.

Add go mod tidy check to Travis config

---

gossip/hub/hub_server/main.go

The replacement should be functionality identical.
Also removed the deprecated way of setting up roundrobin balancing. This might need more work to be fully up to date with gRPC API changes but this change should avoid problems in using a newer version of gRPC.

Remove use of FixedBackendResolver, which has been deleted.

---

gossip/hub/configpb/config.proto

This will become mandatory at some point so we might as well fix it now.

Add go_package option to gossip config proto.

---

binary_transparency/firmware/cmd/flash_tool/flash_tool.go
binary_transparency/firmware/cmd/publisher/publish.go
binary_transparency/firmware/devices/dummy/rom/rom.go
binary_transparency/firmware/internal/verify/bundle.go
binary_transparency/firmware/internal/verify/bundle_test.go

This makes it harder to not compare image hash/firmware measurement when verifying the bundle.

Tighten bundle verification a bit

---

binary_transparency/firmware/api/firmware_metadata.go
binary_transparency/firmware/cmd/ft_monitor/main.go

Adds entries like these to the "normal" (non-verbose) level logging, to easily see details of discovered firmware:
```
I1124 14:39:56.905375 1280867 main.go:123] Found firmware (@0): TalkieToaster/v3 built at 2020-11-24T14:39:47Z with image hash 0xbf2f21936b66a0665883716ea4b1ceda609304ad76dd48f6423128bc36d4cb0fb5effaa9c1f2e328a5cfc25d2cb89a337d4285a8bc3e22dbb99bddbed19e7095
```

Log info from manifest in monitor

---

experimental/batchmap/sumdb/build/map.go

This allows maps with the same number of entries to be computed by different parties to compare equality of the root commitment. Also fixed some parameter checking which wasn't working; cleaning the filepath is more error prone than just using the raw input as it swaps empty input for '.'

Support limiting the number of entries to be committed to by the Map

---

binary_transparency/firmware/docs/design/README.md

- Remove old demo script (we have the new, fuller, one in the FT README)
- Explicitly map the roles/actors to the software from the demo they use

Tidy design doc a bit

---

binary_transparency/firmware/devices/usb_armory/bootloader/boot.go
binary_transparency/firmware/devices/usb_armory/bootloader/ft.go
binary_transparency/firmware/devices/usb_armory/bootloader/main.go
go.mod
go.sum

This gives a ~300% speed up (15.8s down to 5.5s hashing the 64MB partition)

Use DCP for measurement hashing

---

sumdbaudit/audit/database.go
sumdbaudit/audit/service.go
sumdbaudit/cli/clone/clone.go

Added documentation and better console logging when running. None of this is critical, but it's all stuff that is clear after being away from this code for a while. Also made the error handling stricter in case the DB schema is corrupt when reading the latest tree head.
The reason for revisiting this code is that it will be changed to persist the Golden Checkpoint between runs. This improves the security for the stragglers, and it will give the map demo that builds on this access to a Log Checkpoint to write in its Map Checkpoint to allow traceability.

Minor improvements to SumDB auditor

---

go.sum
sumdbaudit/audit/database.go
sumdbaudit/audit/service.go
sumdbaudit/audit/sumdb.go
sumdbaudit/audit/sumdb_test.go
sumdbaudit/cli/clone/clone.go

* Checkpoints for successfully validated trees are stored in a new table in the database
* Clone tool now checks that the local tree is consistent with the previous Golden Checkpoint
* Short-circuit the clone tool if the remote SumDB is reporting the same size as the Golden Checkpoint

Store and check Golden Checkpoints

---

sumdbaudit/README.md
sumdbaudit/audit/database.go
sumdbaudit/cli/clone/clone.go

Also added check for duplicates inline within the tool instead of it being a separate stage that the user needed to perform. Added a force flag to prevent short-circuiting, which is useful when making code changes to the validation.

Updated documentation for SumDB audit/clone tool

---

binary_transparency/firmware/docs/design/README.md

I think this is probably the best I can do without pulling the diagram source into another file, unless you have any other ideas?

Hide diagram source in a details tag

---

sumdbaudit/audit/service.go
sumdbaudit/cli/clone/clone.go

A bunch of the methods that were advertised on the Service were required to be called in order. This pushes this recipe inside a more appropriate method (Sync) and hides the implementation methods away.
I've reordered the methods to put the public ones at the top, and changed the order to match importance/likeliness to be called.

Refactoring to reduce API surface

---

sumdbaudit/audit/service.go
sumdbaudit/cli/mirror/mirror.go

The clone.go tool is intended to be a one-shot tool, and a gentle introduction/demo. This tool is intended to be run as a service which can continually keep a database up to date.
Future work might be to support different databases (e.g. MySQL starts to look reasonable for something like this), or to have some documentation on how to set this up as a Linux service.

Created a mirror service which continually runs

---

.travis.yml
binary_transparency/firmware/integration/ft_functions.sh
binary_transparency/firmware/integration/ft_test.sh
cloudbuild.yaml
gossip/integration/gossip_functions.sh
gossip/integration/gossip_killall.sh
gossip/integration/gossip_test.sh
integration/Dockerfile
scripts/presubmit.sh

Given the future of Travis support for opensource projects is unclear, and we have more control over our destiny using GCP Cloudbuild, add support for migrating our CI over there.

Add CloudBuild CI support

---

sumdbaudit/README.md
sumdbaudit/audit/service.go
sumdbaudit/cli/mirror/mirror.go
sumdbaudit/cli/witness/witness.go

This allows the mirror to be easily upgraded to provide a service which is easy to integrate with from any other tooling.

Added a simple witness to the SumDB examples

---

binary_transparency/firmware/cmd/hacker/modify_bundle/modify_bundle.go
binary_transparency/firmware/integration/ft_functions.sh
binary_transparency/firmware/integration/ft_test.sh

- fixes the integration EXPECT_FAIL test which would have caught this on the signature PR.
- adds a "hacker tool" to easily modify proof bundles
- updates integration test with a new test for checking signatures

Update integration test to cover signature checking on device

---

binary_transparency/firmware/api/update_package.go
binary_transparency/firmware/cmd/flash_tool/flash_tool.go
binary_transparency/firmware/cmd/publisher/publish.go
binary_transparency/firmware/devices/dummy/flash.go
binary_transparency/firmware/devices/dummy/rom/rom.go
binary_transparency/firmware/devices/usbarmory/bootloader/ft.go
binary_transparency/firmware/internal/verify/bundle.go
binary_transparency/firmware/internal/verify/bundle_test.go

- Refactor to improve device-side verification reuse
- Remove redundant signature and proof checks
- Flatten ProofBundle inside UpdatePackage
- Don't force device to parse ProofBundle twice

Tidy up device side

---

binary_transparency/firmware/README.md
binary_transparency/firmware/cmd/emulator/dummy/dummy_emu.go
binary_transparency/firmware/cmd/emulator/dummy/impl/inner_main.go
binary_transparency/firmware/cmd/flash_tool/flash_tool.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/cmd/ft_monitor/ft_monitor.go
binary_transparency/firmware/cmd/ft_monitor/impl/ft_monitor.go
binary_transparency/firmware/cmd/ft_personality/ft_personality.go
binary_transparency/firmware/cmd/ft_personality/impl/ft_personality.go
binary_transparency/firmware/cmd/hacker/modify_bundle/impl/modify_bundle.go
binary_transparency/firmware/cmd/hacker/modify_bundle/modify_bundle.go
binary_transparency/firmware/cmd/publisher/impl/publish.go
binary_transparency/firmware/cmd/publisher/publish.go
binary_transparency/firmware/devices/dummy/flash.go
binary_transparency/firmware/devices/dummy/rom/rom.go
binary_transparency/firmware/devices/usbarmory/flash/flash.go
binary_transparency/firmware/integration/ft_test.sh

- Splits all the `cmd` main files into implementation and bare-minimum `main` files.
- Uses the `cmd` implementations to build a golang integration test.

Split cmds out into implementation and skeleton main files

---

experimental/batchmap/sumdb/README.md
experimental/batchmap/sumdb/build/map.go
experimental/batchmap/sumdb/build/pipeline/entries.go
experimental/batchmap/sumdb/build/pipeline/entries_test.go
experimental/batchmap/sumdb/build/pipeline/log.go
experimental/batchmap/sumdb/build/pipeline/log_test.go
experimental/batchmap/sumdb/mapdb/tiledb.go

If `build_version_list` is provided on the command line then in addition to the 2 hashes for each module+version being committed to in the map, the map will further commit to the list of versions for each module. This is done by building a log for each module, in which the leaves are the versions (in the same order they are found in the input log). The log root hash is committed to in the map under a key which is the hash of the module name.
The list of versions is written to the DB as a JSON serialized list of strings. This is enough information for the log to be reconstructed. This makes all versions for a module discoverable and verifiable.

Support for building logs of versions for a module

---

sumdbaudit/README.md
sumdbaudit/audit/database.go
sumdbaudit/cli/clone/clone.go
sumdbaudit/cli/mirror/mirror.go
sumdbaudit/cli/witness/witness.go

Having the data in a client/server database opens the way for running a mirror in GCP which can be used to build a verifiable map in dataflow. This is infeasible when the database is a local file.
This has been tested with MariaDB 10.5.8.
N.B. This contains a breaking DB schema change. TEXT is not a great choice because at least MariaDB will group by this case insensitively, which surprisingly caused "duplicates" to be identified. Using a binary representation for these fields avoids such false positives.

Added support for client/server SQL databases

---

sumdbaudit/README.md
sumdbaudit/audit/database.go
sumdbaudit/audit/service.go

This short circuit saves a lot of time for mirrors which are updating frequently.

Don't reprocess leaf metadata which is already processed

---

experimental/batchmap/sumdb/mapdb/tiledb.go
experimental/batchmap/sumdb/verification/inclusion.go
experimental/batchmap/sumdb/verify/verify.go
experimental/batchmap/sumdb/versions/versions.go

This builds on #224 by adding a tool to make use of the log of versions. It pulls the list of versions, constructs the log for it, and checks that the map commits to this log. By default it prints only release versions, but the `--all` flag can be used to list ephemeral versions too (e.g. `v0.0.0-20191025170756-f12f9191a1a4`).
This PR looks bigger than it is because the map verification code was extracted/refactored, and github isn't showing the diff.

Tool to list verified versions for a module

---

go.mod
go.sum
sumdbaudit/audit/database.go
sumdbaudit/audit/service.go
sumdbaudit/cli/mirror/mirror.go
sumdbaudit/docker/docker-compose.yml

This also fixes some inconsistency around how we signal no data found from the database layer. We now always return ErrNoDataFound instead of sometimes exposing the raw sql error.
This adds a custom check in the QueryRow.Scan err block for no data found. This appears to be another inconsistency between sqlite and mariadb.
A large TODO from this is to to write tests for the different DB integrations.
Also did `go mod tidy` as things were getting messy.

Docker images use mariadb instead of sqlite

---

experimental/batchmap/sumdb/build/pipeline/log.go
experimental/batchmap/sumdb/build/pipeline/log_test.go
experimental/batchmap/sumdb/versions/versions.go

This addresses the TODO and improves the security of the logs.

Apply prefix domain separation to leaves in version log

---

binary_transparency/firmware/README.md
binary_transparency/firmware/cmd/ft_personality/Dockerfile
binary_transparency/firmware/cmd/ft_personality/ft_personality.go
binary_transparency/firmware/cmd/ft_personality/impl/ft_personality.go
binary_transparency/firmware/cmd/ft_personality/internal/trees/trees.go
binary_transparency/firmware/cmd/ft_personality/internal/trillian/client.go
binary_transparency/firmware/docker-compose.override.yml
binary_transparency/firmware/integration/ft_integration_test.go
go.sum

The personality is now deployed at the same time as Trillian if the docker command in the README is followed.
This requires an extra table of storage for the tree details so that the container can be restarted. The service will now create the tree if it hasn't done so already. This saves quite a lot of human-driven configuration from the start of the demo, which massively streamlines it (and mitigates the risk of anything going wrong from incorrect configuration). Having fewer terminals also lowers the cognitive cost for the audience.

Personality can be deployed in a single command

---

.golangci.yaml

Can revisit if we need different behaviour or upstream adds support for an inclusive language term.

Rely on default value in depguard list type config

---

binary_transparency/firmware/README.md
binary_transparency/firmware/cmd/ftmap/README.md
binary_transparency/firmware/cmd/ftmap/map.go
binary_transparency/firmware/docker-compose.override.yml
binary_transparency/firmware/internal/ftmap/log.go
binary_transparency/firmware/internal/ftmap/mapdb.go
binary_transparency/firmware/internal/ftmap/pipeline.go
binary_transparency/firmware/internal/ftmap/pipeline_test.go

The map is keyed by device ID, and the value is a log which contains the firmware revisions for that device. The log is stored in the database as a flat JSON list of leaf values, and will need to be rehydrated (i.e. the merkle tree recalculated) each time it is used. This puts a limit on how big the sub-logs can be, but that limit is much higher than the cardinalities we'll use for demos.
This requires that the `mysql` docker container has a port exposed outside of the docker network so that the Beam pipeline can access the DB to source the log data.
This pipeline is something of a strawman. By starting with a map of logs, this demonstrates the most complicated map construction and thus all the raw material should be here to allow developers with less experience with Beam to mould this to …

Construct a map of logs from FT log

---

binary_transparency/firmware/api/http.go
binary_transparency/firmware/cmd/ft_monitor/impl/ft_monitor.go
binary_transparency/firmware/cmd/ft_witness/internal/http/witness.go
binary_transparency/firmware/internal/client/client.go
binary_transparency/firmware/internal/client/follower.go
binary_transparency/firmware/internal/crypto/signature.go

This will need to be written again for the annotator client, so factoring this out now to avoid yet more duplication of critical code.
This implementation uses go channels to improve separation of concerns.

Added a LogFollower class to encapsulate common logic

---

binary_transparency/firmware/api/annotation.go
binary_transparency/firmware/cmd/ft_monitor/ft_monitor.go
binary_transparency/firmware/cmd/ft_monitor/impl/ft_monitor.go
binary_transparency/firmware/cmd/ft_personality/internal/http/server.go
binary_transparency/firmware/internal/client/client.go
binary_transparency/firmware/internal/crypto/signature.go

The monitor was already following the log and making judgements on the claims within it. This flag allows the monitor to also function as an annotator and push these judgements back to the log where other parties in the ecosystem can use them.

Upgrade monitor to support annotating

---

binary_transparency/firmware/cmd/ftmap/map.go
binary_transparency/firmware/internal/ftmap/pipeline.go
binary_transparency/firmware/internal/ftmap/pipeline_test.go

The key changes here are:
* Parse the statements, and then partition them into different collections for each logical type
* Return a Result object instead of a bunch of collections (to which we will be adding more collections to)
Because the collections are pre-filtered in the partition stage, some of the DoFns have been
simplified to return the parsed object directly instead of using the emitter (which was needed
to support returning nothing, if the statement was the wrong type).

Refactored the FT Map to lay the foundations for processing annotations

---

binary_transparency/firmware/api/map.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/cmd/ftmap/README.md
binary_transparency/firmware/cmd/ftmap/map.go
binary_transparency/firmware/internal/ftmap/aggregate.go
binary_transparency/firmware/internal/ftmap/aggregate_test.go
binary_transparency/firmware/internal/ftmap/log.go
binary_transparency/firmware/internal/ftmap/mapdb.go
binary_transparency/firmware/internal/ftmap/pipeline.go
binary_transparency/firmware/internal/ftmap/pipeline_test.go

The pipeline now creates an entry for each piece of firmware in the log with an aggregated version of the malware annotation. The aggregation rule is that it is good, and will switch to bad if there exists any malware annotation saying it is bad. We may wish to revise this to be the result of the most recent annotation, but this approach has the benefit of simplicity. And it seems like an edge-case that a release would be classified as malware, and then the scanner would change its mind.
The key in the map is derived from the Log Index of the original FW metadata, and the value is a commitment to a JSON-encoded `AggregatedFirmware`.
The map tiles and aggregated firmware are stored in a DB, but there is not currently any server for returning this data to clients.

Aggregate the FW with the annotations

---

go.sum
tools/tools.go

Without this then mod tidy will start deleting stuff that is actually used, and life becomes a giant struggle. With this, everything will work. Once, and for all.

Added tools.go to point at commands that go modules should know about

---

serverless/cmd/client/client.go
serverless/integration/integration_test.go
serverless/internal/client/client.go

Adds the outline of a simple client which knows how to fetch log data via `file://` or `http[s]://` URLs, and use it to compute and verify inclusion proofs.

[serverless] Add simple client tool

---

binary_transparency/firmware/api/map.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/internal/client/mapclient.go
binary_transparency/firmware/internal/verify/bundle.go
binary_transparency/firmware/internal/verify/bundle_test.go

The plan is to serve the map API primarily via a REST API. The server will use the sqlite DB for the first iteration, but the idea is that this could be swapped for static content similar to the serverless log.
This required a little rerouting to get the FWMeta back to where it could be checked.

Client sketch for map checks

---

serverless/internal/storage/fs/fs.go

This change allows clients who only hold the leaf primage to figure out the sequence number for that leaf and build the corresponding inclusion proof.

[serverless] Use leafhash files as hash->seq index

---

serverless/integration/integration_test.go

Adds coverage for inclusion proofs, and accessing the log via both `file://` and `http://` schemes.

[serverless] Extend integration test

---

binary_transparency/firmware/cmd/ftmap/map.go
binary_transparency/firmware/internal/ftmap/mapdb.go

All client code wants to ensure it has a valid connection to the map, so it makes sense to roll these together.

Ensure MapDB is initialized when returned.

---

binary_transparency/firmware/cmd/ftmap/map.go
binary_transparency/firmware/cmd/ftmapserver/impl/ftmapserver.go
binary_transparency/firmware/cmd/ftmapserver/impl/ftmapserver_test.go
binary_transparency/firmware/cmd/ftmapserver/impl/mock_mapreader.go
binary_transparency/firmware/internal/ftmap/mapdb.go
binary_transparency/firmware/internal/ftmap/pipeline.go

The log checkpoint was actually just a hash. We now persist it as a LogRootV1, and then convert that into an api.LogCheckpoint in the server.

Make map checkpoint contain valid log checkpoint

---

binary_transparency/firmware/cmd/flash_tool/flash_tool.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/internal/client/mapclient.go

This checks the log checkpoint in the map checkpoint is good and consistent with the log checkpoint otherwise relied on. It currently then fails because the inclusion proof is not yet implemented. Fortunately, the map checks are skipped entirely if the map_url flag is not provided.

Allow flash tool to actually call the map server

---

binary_transparency/firmware/api/map.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/internal/ftmap/aggregate.go
binary_transparency/firmware/internal/ftmap/mapdb.go
binary_transparency/firmware/internal/ftmap/pipeline_test.go

Keeping this forces the map server to be able to return the raw log entries. This could be done, but requires either a connection to another DB, or duplicating data. Furthermore, the client already has this data and was just asserting equality. Given that we've already checked log consistency, we're already convinced we have the same view of the log data.

Remove unused nested field

---

binary_transparency/firmware/api/map.go
binary_transparency/firmware/cmd/ftmapserver/impl/ftmapserver.go
binary_transparency/firmware/cmd/ftmapserver/impl/ftmapserver_test.go
binary_transparency/firmware/cmd/ftmapserver/impl/mock_mapreader.go
binary_transparency/firmware/internal/client/mapclient.go

The map server now supports:
* lookup of tiles by the path to the root of the tile
* getting an aggregation for FW logged at a given index
Updated the client pseudocode to better match the shape of the server API.
This is based on top of #302.

Implemented map server methods

---

serverless/README.md
serverless/cmd/client/client.go

This helps the client detect splitview attacks between invocations.

[serverless] Client track state

---

serverless/api/state.go
serverless/internal/client/client.go
serverless/internal/log/integrate.go
serverless/internal/storage/fs/fs.go
serverless/internal/storage/fs/fs_test.go

Storing the compact range hashes in the log state file could be seen as an optimisation, but it's not _strictly_ necessary as we can calculate and fetch the tiles/nodes based on the state's `Size` alone.
So for now at least, and to bring the log state file closer to the common minimal set of fields, remove these hashes from the on-disk state.

[serverless] Remove compact range hashes from log state file

---

serverless/api/state.go
serverless/api/state_test.go
serverless/internal/client/client.go
serverless/internal/log/integrate.go
serverless/internal/storage/fs/fs.go

This PR implements a simple custom text format for serialising the log tiles, rather than directly using JSON.
The format is trying to find a sweet spot between a full binary representation and something which is easy to read/debug but without too much extra clutter.
An example tile in this format looks like this:
```
32
4
qsZs16ec5AEtgHYv6O7Dp38i0cpBRcP0zuAi5+/NWZ0=
z9+lOZmJFyF/Mpcpq483zbJbCGFye9Qq0qH5xQ+3UyM=
ycWD0Xb0jgtbC1nQ6Of7QWpFxlASqs3nQC0vmQ8mxcw=
qiSZ0B/Hha39/LXy6yETE+CZxGE0SDtDM2IjhxLOGAo=
hd9aDSQrndkekVXXrt2weXcStDte0WrHMwKwHZCQLo4=
XnuygG2bXSR9CnvgLx9AlExUsMD1pm9ouR2l1KwsQE4=
Xa/RR4kVQaZZiL5oa3epz0H4dgtdELmfCd3bpTyZVnA=
```

[serverless] Store tiles in a slightly leaner format than JSON

---

serverless/deploy/github/sequence_and_integrate/action.yaml

`github` isn't recognised as an expression for some reason, so just use a static string.

[serverless] Fix concurrency

---

binary_transparency/firmware/api/map.go
binary_transparency/firmware/cmd/flash_tool/flash_tool.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/cmd/ftmap/map.go
binary_transparency/firmware/integration/ft_integration_test.go
binary_transparency/firmware/internal/client/mapclient.go
binary_transparency/firmware/internal/client/mapclient_test.go

The map checkpoint and tiles are now fetched from the server. `mapclient` generates a compact inclusion proof from this data, which is then verified by `flash_tool`.
This architecture is belt and braces, but my thinking evolved during this PR. Initially the plan was to have a very simple server which could work like the "serverless" log and just serve static content. However, as I started to write the map client, I realized that this pushed a lot of work onto the clients, which might have limited compute power. I've thus written the logic in the `mapclient` as effectively untrusted, which means that this work could be done on a server, meaning much less hashing and space requirements for the verifying client.
Raising this as a draft PR to get an early review on this approach, before I …

Flash tool uses aggregations from map to check for malware

---

serverless/cmd/integrate/main.go
serverless/cmd/sequence/main.go
serverless/integration/integration_test.go
serverless/internal/log/integrate.go
serverless/internal/storage/fs/fs.go
serverless/internal/storage/fs/fs_test.go

Decouple the log state storage a bit - we really want to be able to store an envelope which _contains_ the log state, rather than just the log state itself (e.g. if the tooling wants to sign the log state), so let the caller decide what/how to do that before they ask the storage to write the bytes.

[serverless] Expose log state serialisation/storage to tools

---

binary_transparency/firmware/README.md
binary_transparency/firmware/cmd/ft_monitor/ft_monitor.go
binary_transparency/firmware/cmd/ft_monitor/impl/ft_monitor.go
binary_transparency/firmware/cmd/ftmap/README.md
binary_transparency/firmware/integration/ft_integration_test.go

Without this, the monitor starts from the beginning of the log on each run. This is wasted effort in the best-case, but can actually cause a lot of spam annotations to the log in the worst case.
The state file can always be removed locally if the monitor code is updated and needs to process the whole log again.

Persist the monitor state to avoid repeated work

---

serverless/cmd/client/client.go
serverless/internal/client/client.go

This updates the client's local cached state forward to the latest log checkpoint.
Using `-v=1` will print out the checkpoint and proof data:
```
I0527 15:49:43.596880 3352634 client.go:215] Original checkpoint:
Log Checkpoint v0
5
41smjBUiAU70EtKlT6lIOIYtRTYxYXsDB+XHfcvu/BE=
— github.com/AlCutter/serverless-test/log KANRkZyJJHaTBkJwLH6Qa+tBAgZvX8tN2putKEmEe8QqYnou10EoY2uZEY2PKXPnoJgFGk1AdYbUcnDYE8UgbG87owA=
I0527 15:49:43.847665 3352634 client.go:336] Built consistency proof [b9e1d62618f7fee8034e4c5010f727ab24d8e4705cb296c374bf2025a87a10d2 aac66cd7a79ce4012d80762fe8eec3a77f22d1ca4145c3f4cee022e7efcd599d 89d0f753f66a290c483b39cd5e9eafb12021293395fad3d4a2ad053cfbcfdc9e 29e40bb79c966f4c6fe96aff6f30acfce5f3e8d84c02215175d6e018a5dee833]
I0527 15:49:43.847794 3352634 client.go:227] Updated …
```

[serverless] Add update client command

---

clone/README.md
clone/cmd/ctclone/Dockerfile
clone/cmd/ctclone/ctclone.go
clone/cmd/ctclone/ctclone_test.go
clone/internal/download/batch.go
clone/internal/download/batch_test.go
clone/internal/download/http.go
clone/internal/logdb/database.go
clone/internal/logdb/database_test.go

The tool clones leaves from the log as quickly as possible to a MySQL instance provisioned by the user. This is the foundation for doing local processing of all data, such as building a verifiable map.
This is optimized very heavily towards downloading a large amount of data quickly, while respecting the log if it asks the client to back off. Missing features:
* downloading/persisting checkpoints & verifying the leaf data
* terminating cleanly when the end of the log is reached
The design ensures that leaves are never written without any gaps in order to simplify the local state required.

Tool that bulk downloads CT logs, respecting backoffs

---

serverless/deploy/github/leaf_validator/entrypoint.sh

Complain if we find:
- a file in the log directory, but outside of the `leaves/pending` directory
- pending leaves AND modifications outside the log directory

Tweak leaf validator

---

serverless/client/client.go

The severless client relies on the fetcher correctly returning `os.ErrNotExist` when the requested resource does not exist.

[serverless] Update Fetcher comment explaining contract

---

witness/ethereum/Pipfile.lock

This subdir only has one explicit dep-- `eth-brownie`. I ran `pipenv update eth-brownie`, which should also update brownie's deps. Hopefully brownie's latest version has new enough versions of these deps to make dependabot stop complaining 😄

ethwit - updating package versions

---

serverless/deploy/github/leaf_validator/entrypoint.sh

The LEAF variable was mistakenly removed in 1e7cf8baf1197a10ab67ad27ce53347186172725.

Fix undefined variable

---

binary_transparency/firmware/cmd/ftmap/map.go
experimental/batchmap/sumdb/build/map.go

This can cause problems with flag parsing in Dataflow if not above flag checks

Move beam.Init further up

---

scripts/presubmit.sh
serverless/cmd/feeder/Dockerfile
serverless/cmd/feeder/feed-to-github
serverless/cmd/feeder/impl/feeder.go
serverless/cmd/feeder/main.go
serverless/deploy/docker/witness/README.md
serverless/deploy/docker/witness/docker-compose.yaml
witness/golang/cmd/witness/Dockerfile

- Add `Dockerfile`s for `witness` and `feeder`
- Add `docker-compose.yaml` for running a combined `witness` and `feeder`
- Update `feed-to-github` to support running inside docker, and add option to run continuously

[Serverless] Add docker github feeder

---

clone/cmd/ctclone/ctclone.go
clone/cmd/ctverify/ctverify.go
clone/internal/verify/verify.go
clone/internal/verify/verify_test.go
clone/logdb/database.go
clone/logdb/database_test.go

Checkpoints are stored with the compact range, which allows the log contents to be verified incrementally.
Verified checkpoints are now stored by the `ctverify` tool. Upon verifying a new checkpoint, the latest verified checkpoint will be loaded and only the leaves added since that checkpoint will directly be checked.
This is a performance improvement for verification, and it also provides tooling that reads from the log (e.g. map building code) to find the log checkpoints. This code can either trust the local DB hasn't been modified since verification, or it can re-verify all leaves against the checkpoint if desired. In the case of the map, the log checkpoint used will be embedded within the map checkpoint in order to complete an audit trail.

Support writing & reading checkpoints in DB

---

serverless/client/client.go
serverless/client/client_test.go

The consistency checking function ignores the first pair of checkpoints.
This change adds a test that failed, and fixes it.

serverless: Fix consistency checks

---

clone/cmd/ctclone/ctclone.go
clone/internal/download/batch.go
clone/internal/download/batch_test.go

The Bulk method now takes ownership of the channel too. This simplifies control flow.
This came up as part of another piece of work and has been separated into its own PR.

Combine result and error channels together

---

serverless/experimental/wasm/index.html
serverless/experimental/wasm/main.go

- This allows us to use the `client` package
- Use the `client` package in the monitor to do consistency checking of CPs

[Serverless] Add checkpoint sigs to the wasm experiment

---

serverless/experimental/wasm/index.html
serverless/experimental/wasm/main.go

- Print out log entries in the monitor console
- Use compact range to verify consistency and inclusion
(currently stacked on #417 and #418, will rebase)

[Serverless] Make WASM monitor inspect log entries

---

clone/cmd/ctclone/ctclone.go
clone/cmd/ctclone/ctclone_test.go
clone/internal/download/batch.go
clone/internal/download/batch_test.go

Previously this tool kept attempting to download full batches until it encountered too many errors and died. This would happen after it had overshot the end of the log.
This now fetches the latest checkpoint from the log and only downloads the number of leaves that commits to. After downloading all of the leaves, it verifies that the downloaded leaves match the checkpoint commitment. Once verified, this checkpoint is stored in the database.

Download leaves up to the latest checkpoint and verify result

---

serverless/cmd/integrate/main.go
serverless/cmd/sequence/main.go
serverless/experimental/wasm/main.go
serverless/integration/integration_test.go
serverless/internal/log/integrate.go
serverless/internal/storage/fs/fs.go
serverless/internal/storage/fs/fs_test.go
serverless/internal/storage/webstorage/fs.go

Storage was previously parsing a signed note as a checkpoint, now the caller of `log.Integrate` passes in the checkpoint data.

[Serverless] no checkpoint state in storage

---

witness/golang/cmd/witness/internal/witness/witness.go
witness/golang/cmd/witness/internal/witness/witness_test.go

This string shouldn't change once the log is configured. If the string changes (e.g. new version) then this is effectively a new log.

Add a check that the log string doesn't change after TOFU

---

sumdbaudit/audit/service.go
sumdbaudit/audit/sumdb.go
sumdbaudit/audit/sumdb_test.go

This can probably be better used in this witness, but for now preserve the old behaviour.
This API is being used by the new feeder being implemented, and partial tile fetching is important for that.

Support fetching partial tiles

---

sumdbaudit/audit/database.go

Newer versions of MariaDB use `offset` as a reserved word. Renamed to `toffset` to sidestep the problem.
This is a breaking change for users upgrading from a previous version; the new code will fail to read this column. The solution is to manually rename the column in the DB to `toffset`, or to recreate the DB and mirror from a clean slate.

Breaking change: rename column in DB

---

sumdbaudit/docker/witness/Dockerfile

This got broken when `witness` directory was added at the top level

Fix Docker build

---

serverless/cmd/feeder/impl/feeder.go
serverless/cmd/feeder/impl/feeder_test.go
witness/golang/client/http/witness_client.go
witness/golang/cmd/witness/internal/http/server.go

The witness client returns the latest checkpoint when it is available so that feeders don't need to make another call to GetCheckpoint.
It also includes a small fix on the witness to not add a trailing newline to the checkpoint when we return StatusConflict. This avoids stripping characters on the client to avoid malformed notes.

Witness client: Update returns latest Checkpoint

---

sumdbaudit/witness/README.md
sumdbaudit/witness/cmd/feeder/Dockerfile
sumdbaudit/witness/cmd/feeder/main.go
sumdbaudit/witness/cmd/feeder/main_test.go
sumdbaudit/witness/docker-compose.yaml
sumdbaudit/witness/witness.config

This constructs compact ranges from the SumDB API and feeds these to the witness.
Setting this up with docker is fairly simple and is documented in the README.

SumDB feeder for the generic witness

---

serverless/api/state_test.go
serverless/integration/integration_test.go

Running the integration tests in parallel saves a good minute on the total test time for `go test ./...`.
The change to the marshal test to only check roundtripping for a few interesting tile sizes drops the test time from 8+s to under 1s.

Speed up serverless tests

---

cloudbuild.yaml
scripts/presubmit.sh

- Adds some more parallel steps in the CloudBuild config for building docker images, action images, wasm, running linters, etc.
- Removes obsolete `go test -i` flag
Last couple of CB runs with these changes are down to < 4m.

Speed up CloudBuild runs

---

clone/internal/download/batch.go

The backoff doesn't accumulate stuckness over time, which the previous wisdom had assumed.
I had written an adaptive, shared backoff for all the workers to use. In testing however, it performs about as well as this one. This is simpler, so I'm tempted to stick with this for the time being.

Removed TODO which was misleading

---

clone/internal/download/batch.go
clone/internal/download/batch_test.go

Subtracting too large a value from uint64 causes a wrap around to a super large number that will never be reached. Obvious now, but with this much concurrency it was easy to assume deadlock.

Fixed hang in corner case where batch size > tree size

---

sumdbaudit/audit/database.go
sumdbaudit/audit/service.go
sumdbaudit/cli/clone/clone.go
sumdbaudit/cli/mirror/mirror.go
sumdbaudit/cli/witness/witness.go
sumdbaudit/client/sumdb.go
sumdbaudit/client/sumdb_test.go
sumdbaudit/witness/cmd/feeder/main.go

This is generally useful and should be usable without pulling in the Service or Database. More importantly, Database defines flags which conflict with the flags I'm trying to define and use in the sumdbclone tool based on the ctclone system.

Move sumdb client into separate package

---

sumdbaudit/witness/cmd/feeder/main.go

Future work could be done to make this exit after some duration (or number of attempts) without success. For now though, this is strictly better than restarting (or exiting) what should be a long-lived service

Make the feeder warn instead of exiting on failure

---

clone/README.md
clone/cmd/ctclone/README.md
clone/cmd/sumdbclone/Dockerfile
clone/cmd/sumdbclone/README.md
clone/cmd/sumdbclone/sumdbclone.go

This is consistent with the ctclone tool and uses much of the same machinery to get the job done. There is a little additional complexity here where we need to always be downloading a tile per worker to realize the parallelism dream. This means that when the previous download finished mid-tile, we need to do a little neatening up before we can invoke the Bulk command. Otherwise, this drops in cleanly if I say so myself.

SumDB clone tool that downloads the DB quickly 

---

serverless/deploy/github/distributor/README.md
serverless/deploy/github/distributor/combine_witness_signatures/README.md
serverless/deploy/github/distributor/combine_witness_signatures/action.yaml
serverless/deploy/github/distributor/combine_witness_signatures/combine_witness_signatures.go
serverless/deploy/github/distributor/combine_witness_signatures/entrypoint.sh
serverless/deploy/github/distributor/combine_witness_signatures/example_config.json
serverless/deploy/github/distributor/combine_witness_signatures/go.mod
serverless/deploy/github/distributor/combine_witness_signatures/go.sum
serverless/deploy/github/distributor/combine_witness_signatures/internal/distributor/state.go
serverless/deploy/github/distributor/combine_witness_signatures/internal/distributor/state_test.go

Update serverless witness actions to be a distributor
Part of #464

[Serverless] Add distributor action

---

integration/Dockerfile
serverless/deploy/github/distributor/combine_witness_signatures/Dockerfile
serverless/deploy/github/log/sequence_and_integrate/Dockerfile

This updates things that were explicitly using 1.16 things, and makes the reference to the "latest" version of buster explicitly locked to a version in the same way that we have done in the main trillian repo.

Update go tooling to 1.17 for docker images

---

formats/log/note.go
formats/log/note_test.go

This handles parsing the note, and verifying that the log has signed it. Optionally, other required verifiers can be specified. If these are provided, then all of the signatures from these verifiers must be present.
This also checks the first line of the message is the LogID that was set to be expected when the parser was constructed. This part isn't decided (other proposals exist for where the LogID should live) but I've added this check here as a strawman.

A note parser and verifier for checkpoints 

---

helloworld/client.go
helloworld/helloworld_test.go
sumdbaudit/witness/cmd/feeder/main.go

Also made client.UpdateChkpt declared on the pointer to fix no-op assignment bug spotted while doing this.
There are plenty of other places also doing checkpoint parsing, but the origin string is not easily available so these changes will require more work.

Used log.ParseCheckpoint in a few easy places

---

formats/log/note.go
formats/log/note_test.go
helloworld/client.go
helloworld/helloworld_test.go
sumdbaudit/witness/cmd/feeder/main.go

This makes it much easier in the common case that there aren't additional verifiers

Reordered parameters to ParseCheckpoint

---

sumdbaudit/witness/README.md

Example code prints public then private, which is ever so slightly unexpected given suggested bash is the other way around.

minor order of operations edit

---

binary_transparency/firmware/api/http.go
binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
binary_transparency/firmware/cmd/ft_monitor/impl/ft_monitor.go
binary_transparency/firmware/cmd/ft_witness/internal/http/witness.go
binary_transparency/firmware/cmd/ft_witness/internal/http/witness_test.go
binary_transparency/firmware/devices/dummy/rom/rom.go
binary_transparency/firmware/devices/usbarmory/bootloader/ft.go
binary_transparency/firmware/internal/client/client.go
binary_transparency/firmware/internal/client/wclient.go
binary_transparency/firmware/internal/verify/bundle.go
binary_transparency/firmware/internal/verify/bundle_test.go
formats/log/note.go
formats/log/note_test.go
helloworld/client.go
helloworld/helloworld_test.go
sumdbaudit/witness/cmd/feeder/main.go

This change identified a few tests that were still passing using the old origin string that was replaced in #470. I think this is compelling that reusing the same parsing code reduces bugs.

Perform checks on Origin consistently within FT demo

---

serverless/cmd/feeder/github/main.go
serverless/cmd/feeder/impl/feeder.go
serverless/cmd/feeder/impl/feeder_test.go
serverless/cmd/feeder/main.go

Keep things simple for the moment, we can re-add support for 1:N later if need be.

[Serverless] Simplify to one witness per feeder

---

sumdbaudit/witness/witness.config
witness/golang/README.md
witness/golang/cmd/witness/example.conf
witness/golang/cmd/witness/impl/witness.go
witness/golang/cmd/witness/internal/http/server_test.go
witness/golang/cmd/witness/internal/witness/witness.go
witness/golang/cmd/witness/internal/witness/witness_test.go

Previously the Origin was only determined when the first checkpoint was provided for a log. That isn't wrong per se, but the Origin should be set at the same time as the public key. This also allows the witness code to reuse the common checkpoint parsing code.

Witness: move expected Origin to log config

---

serverless/client/client.go
serverless/client/witness/consensus.go
serverless/client/witness/consensus_test.go
serverless/cmd/client/client.go
serverless/integration/integration_test.go

This adds basic support in the serverless client for the experimental witness/distributor.
Example usage:
```bash
$ export SERVERLESS_LOG_PUBLIC_KEY=github.com/AlCutter/serverless-test/log+28035191+AVtQ/9lW+g90rQY3+pODJvMQ8X/tTvh/EuvCDLSmUk4S
$ go run ./serverless/cmd/client/ \
--log_url=https://raw.githubusercontent.com/AlCutter/serverless-test/master/log \
--log_id=serverless-test \
--origin=github.com/AlCutter/serverless-test/log \
--distributor_url=https://raw.githubusercontent.com/AlCutter/serverless-test/master/distributor/ \
--witness_sigs_required=2 \
--witness_public_key=${HOME}/trillian/serverless-test/witnesskeys/can_i_get.pub \
--witness_public_key=${HOME}/trillian/serverless-test/witnesskeys/wolsey_bank_alfred.pub \
--v=2 \
--logtostderr \
update
I0908 12:39:56.010538 3362835 …
```

[Serverless] Add support for witness/distributor in client

---

serverless/client/client.go

This will also check the signatures and the origin. Checking this at construction makes it easier to reason about the invariants of the LatestConsistent checkpoint - it should always be signed by CpSigVerifier and have the expected Origin string.

Replaced the last untrusted Checkpoint parsing with defensive code

---

serverless/client/client.go
serverless/client/witness/consensus.go

Don't force serverless clients to inherit `glog` dependency.
This removes forcing a bunch of flags on folks writing CLI tooling for serverless logs.

[Serverless] Remove glog dep from client

---

serverless/cmd/distribute/example_config.yaml
serverless/cmd/distribute/github/Dockerfile
serverless/cmd/distribute/github/main.go
serverless/cmd/feeder/github/main.go
serverless/internal/github/github.go

This allows a couple of likely modes of operation to happen:
* Private witnesses can run this to distribute their checkpoints
* Public witnesses can be referenced from a 3rd party to increase the reach of their distribution

Tool to push from witness->serverless distributor

---

formats/log/identifier.go
formats/log/identifier_test.go
serverless/config/example_log_config.yaml
serverless/config/log.go
witness/golang/cmd/witness/example_config.yaml
witness/golang/cmd/witness/impl/witness.go

This is determinstic given an origin string and public key, and is guaranteed to contain no characters that could abuse filesystem or URL path handling.

Proposal for log identifier

---

serverless/deploy/github/distributor/combine_witness_signatures/go.mod
serverless/deploy/github/distributor/combine_witness_signatures/go.sum

Use latest trillian-examples code in `combine_witness_signatures` submodule so that derived log ID works there too.

[serverless] Update combine_witness_signatures dep

---

serverless/deploy/github/distributor/README.md

The most significant is that the config file for auto-merge didn't work.

Fixed typos in README

---

serverless/deploy/github/distributor/README.md

This doesn't trigger the main branch push trigger for some reason. It could be that there's no harm in leaving this uncommented and it just won't trigger if such a workflow doesn't exist, but I'm erring on the side of caution.

Added trigger for auto-merge completing

---

helloworld/helloworld_test.go
witness/golang/api/http.go
witness/golang/cmd/witness/internal/witness/witness.go

Sign checkpoints only at the point at which we're sure they're consistent.
Oh, and I fixed a typo I noticed the other day :).

[witness] no more optimistic signing

---

witness/golang/cmd/witness/impl/witness.go

Builds upon #539 to add support for Sigstore style ECDSA signatures in the witness, and can be used with the feeder added in #540.

Adds support for SigStore/Rekór signatures to witness

---

feeder/cmd/rekor_feeder/main.go
internal/feeder/feeder.go

The JSON proof response encodes hashes as hex strings rather than base64, so we need to decode manually.

Fix proof generation in Sigstore feeder

---

witness/golang/client/http/witness_client.go
witness/golang/cmd/witness/internal/http/server.go
witness/golang/cmd/witness/internal/http/server_test.go
witness/golang/cmd/witness/internal/witness/witness.go

- tweaked the returned `status.Code` for some conditions
- added a bit of logging/passing HTTP status text through into `error`s
- fixed bug where CP wasn't being written as comments suggested

Improve witness status code responses

---

feeder/cmd/rekor_feeder/example_config.yaml
internal/note/note_verifier.go
internal/note/note_verifier_test.go

- Make the verifier string format be like standard note ones
- Rename from SigStoreECDSA -> ECDSA since this is now agreed to be the definition of note's algoID 2

Fix up the ECDSA verifier string format

---

feeder/cmd/pixel_bt_feeder/Dockerfile
feeder/cmd/pixel_bt_feeder/README.md
feeder/cmd/pixel_bt_feeder/example_config.yaml
feeder/cmd/pixel_bt_feeder/internal/convert.go
feeder/cmd/pixel_bt_feeder/internal/convert_test.go
feeder/cmd/pixel_bt_feeder/main.go

Adds a first cut of a feeder from the Pixel BT log to the generic witness.

Add a Pixel BT feeder

---

feeder/cmd/pixel_bt_feeder/README.md
feeder/cmd/pixel_bt_feeder/standalone.conf/feeder.yaml
feeder/cmd/pixel_bt_feeder/standalone.conf/pixelwitness.yaml
feeder/cmd/pixel_bt_feeder/standalonewitness.docker-compose.yaml

This allows a witness for the Pixel Binary Transparency log to be brought up easily. To do so, key material must be generated (example code is linked in the compose file), then provided in the feeder.yaml and via environment variables to docker-compose.

Docker compose file for Pixel BT log witness

---

internal/feeder/feeder.go
internal/feeder/feeder_test.go

This is much friendlier for users trying to set this up; previously the choices when testing configs/integration were: a) set the interval to a small number for first iteration; or b) wait for some minutes each time.
Switch linear retry for exponential backoff when feeding.

Feed checkpoints immediately instead of waiting for the interval first

---

feeder/cmd/pixel_bt_feeder/example_config.yaml
feeder/cmd/pixel_bt_feeder/main.go
feeder/cmd/rekor_feeder/example_config.yaml
feeder/cmd/rekor_feeder/main.go
internal/feeder/feeder.go
internal/feeder/feeder_test.go
serverless/cmd/feeder/example_config.yaml
serverless/cmd/feeder/main.go

Having the public key around in feeders is a remnant from when the feeder/verifier/distributor roles were bundled together, but since the feeder's only job is to send checkpoints _into_ the witness it's unnecessary.
Removing it simplifies code & config.

[Witness] Remove pubkey from feeders

---

serverless/cmd/distribute/example_config.yaml
serverless/cmd/distribute/github/main.go
serverless/config/example_witness_config.yaml
serverless/config/witness.go

Anywhere it is needed, it can be provided as a flag. This makes it far simpler to deploy with docker.

Removed the witness public key from the config files

---

serverless/cmd/client/client.go

If the `output_checkpoint` flag is set, it's helpful to always create the file with the latest known checkpoint, regardless of whether it's just been updated.

[Serverless] Always write out checkpoint on update

---

feeder/cmd/pixel_bt_feeder/main.go
feeder/cmd/rekor_feeder/main.go
internal/feeder/pixelbt/convert.go
internal/feeder/pixelbt/convert_test.go
internal/feeder/pixelbt/pixel_feeder.go
internal/feeder/rekor/rekor_feeder.go
internal/feeder/serverless/serverless_feeder.go
internal/feeder/sumdb/sumdb_feeder.go
internal/feeder/sumdb/sumdb_feeder_test.go
serverless/cmd/feeder/main.go
sumdbaudit/witness/cmd/feeder/main.go

This allows alternative main files to be created for these feeders, e.g. TamaGo unikernels.
The delta appears large, but is almost entirely mechanical moving of existing code.

[Witness] Extract feeder implementations from their main files

---

witness/golang/cmd/witness/impl/witness.go
witness/golang/cmd/witness/internal/witness/witness.go

Fixes a couple of issues with the witness' storage implementation:
1. The call to `Exec` to update checkpoints can silently fail, ensure we catch those errors
2. Errors caught by the fix to (1) were seen for concurrent update RPCs (where updates are for distinct logs), resulting in a `database locked` error. Avoid this situation entirely by limiting the number of concurrent connections.
Also simplify the SQL used for the update.

[Witness] Fix DB related issues

---

witness/README.md

This expands the list to all known feeders, but suggests not running them individually as we have a better solution in the omniwitness.

Updated docs on feeders

---

witness/golang/omniwitness/distributor_configs/witness.yaml
witness/golang/omniwitness/feeder_configs/pixel.yaml
witness/golang/omniwitness/witness_configs/witness.yaml

This was updated in the last week or so. Witness operators will need to update their config files to this new version and redeploy. I recommend also updating the docker images to more recent versions too.

Updated Pixel BT public key

---

clone/cmd/sumdbclone/sumdbclone.go
feeder/cmd/pixel_bt_feeder/main.go
feeder/cmd/rekor_feeder/main.go
internal/feeder/pixelbt/pixel_feeder.go
internal/feeder/rekor/rekor_feeder.go
internal/feeder/serverless/serverless_feeder.go
internal/feeder/sumdb/sumdb_feeder.go
serverless/cmd/feeder/main.go
sumdbaudit/cli/clone/clone.go
sumdbaudit/cli/mirror/mirror.go
sumdbaudit/cli/witness/witness.go
sumdbaudit/client/sumdb.go
sumdbaudit/witness/cmd/feeder/main.go

All feeders now take a http client used for all http connections. Furthermore, they all take the interface definition for a witness instead of the http client implementation. This allows different implementations to be passed in
All clients configure the http client with a timeout. Previously, it doesn't look like the timeout was actually being used in many cases.

Improve feeder interfaces and timeout handling

---

binary_transparency/firmware/devices/usbarmory/bootloader/boot.go
binary_transparency/firmware/devices/usbarmory/bootloader/elf.go
binary_transparency/firmware/devices/usbarmory/bootloader/main.go
go.mod
go.sum

Fixed breaking changes from various refactorings. A newer version of tamago is needed to get the imx-usbnet package working for the unikernel witness in #601.

Updated tamago to latest version

---

clone/cmd/sumdbclone/sumdbclone.go
internal/feeder/sumdb/sumdb_feeder.go
sumdbaudit/cli/clone/clone.go
sumdbaudit/cli/mirror/mirror.go
sumdbaudit/cli/witness/witness.go
sumdbaudit/client/sumdb.go
witness/golang/omniwitness/configs.go
witness/golang/omniwitness/feeder_configs/sumdb.yaml
witness/golang/omniwitness/internal/omniwitness/omniwitness.go

Make SumDB Feeder configured similarly to the others
This feeder was implemented before the others, and at the time it seemed like a good idea to have it take the URL from the key name. This now takes the URL explicitly, which makes it consistent with the others. The config for this feeder in the omniwitness now lives in a config file.

sumdbconfig

---

feeder/ethereum/yarn.lock
witness/ethereum/yarn.lock

We're getting an increasing number of security warnings. Hopefully this will address some of them. I haven't tested this, hopefully the presubmits will run some tests to ensure this hasn't changed functional behaviour.

Run 'yarn upgrade' to fix some security warnings

---

serverless/client/client.go
serverless/client/client_test.go

Happens if we specify a non-existing "to-size" in a consistency proof
Signed-off-by: Morten Linderud <morten@linderud.pw>

serverless/client: Don't panic when tile is unreachable

---

internal/distribute/github/distribute.go
internal/feeder/feeder.go
internal/feeder/pixelbt/pixel_feeder.go
internal/github/github.go

This makes it clearer to follow the activity of all threads in the omniwitness at --v=1

Improved log messages for feeder and distributor

---

internal/feeder/serverless/serverless_feeder.go

This will cause this feeder to bail when the context becomes cancelled. I'm surprised there isn't a lint check for calling one of the methods like context.Background when there is already a ctx in scope.

Use the context passed in

---

witness/golang/omniwitness/internal/omniwitness/omniwitness.go
witness/golang/omniwitness/monolith/monolith.go
witness/golang/omniwitness/usbarmory/main.go

If the github authentication details are provided then the distributors
will be started.
This also adds  goroutine start/stop info logging, which can be
useful in case there are any goroutines that exit early, and any that
don't automatically exit when the context is cancelled.

Unikernel omniwitness can now distribute

---

feeder/cmd/pixel_bt_feeder/main.go
feeder/cmd/rekor_feeder/main.go
serverless/cmd/distribute/github/main.go
serverless/cmd/feeder/main.go
sumdbaudit/witness/cmd/feeder/main.go
witness/golang/client/http/witness_client.go

* client is constructed via a method instead of directly
* removed the log sig verifier which was never read
* http.Client initialization pushed out to the main packages

Misc witness HTTP client improvements

---

witness/golang/omniwitness/internal/omniwitness/omniwitness.go
witness/golang/omniwitness/monolith/monolith.go
witness/golang/omniwitness/usbarmory/main.go

The omniwitness now takes the persistence layer as an additional argument. The usbarmory version still uses the inmemory version. The monolith version uses inmemory by default, but if --db_file is provided then it will persist the results using sqlite.

Monolith omniwitness can use SQL persistence

---

cloudbuild_docker.yaml
witness/golang/omniwitness/monolith/Dockerfile

This may replace the docker-compose version of the omniwitness, at least as our primary recommendation of how to run this. The primary benefit is that it's much simpler; there's only one executable to launch and the only config it takes are those that are user-specific. All of the details of the logs and github distributors are baked into the binary. This should make it far easier to ensure everyone is running the same configuration of the omniwitness as logs are added, etc.
There is explicitly no plan to prevent users running these components flexibly, this is simply a case of having the omniwitness very opinionated to encourage simple adoption.

Build the monolithic omniwitness as Docker image

---

cloudbuild_docker.yaml

Error in triggered runs is 'Your build failed to run: generic::invalid_argument: generic::invalid_argument: invalid value for 'build.substitutions': key in the template ENTRIES_DIR is not a valid built-in substitution'.

Fix cloudbuild_docker

---

cloudbuild.yaml
cloudbuild_docker.yaml

We're getting timeouts building the docker images. Hopefully this will help. And doing it in both cloudbuild files keeps them consistent.

Use faster and bigger machines for cloud build

---

internal/github/github.go
serverless/cmd/distribute/github/main.go
witness/golang/omniwitness/internal/omniwitness/omniwitness.go

This was implicitly using the default client, which doesn't work on the USB Armory as it requires a custom client. This change sets the client via a context, which is the way the oauth2 libraries like to do it. This could also have been implemented by putting the client in the context at a higher level instead of passing it around, but the explicit argument passing is clearer and more consistent with how we've implemented the rest of this code.

Override http.Client used by distributors

---

witness/ethereum/Pipfile.lock

The following command was executed to update the pip dependencies.
```zsh
@roger2hk ➜ /workspaces/trillian-examples/witness/ethereum (master) $ pipenv update
Running $ pipenv lock then $ pipenv sync.
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success! 
Updated Pipfile.lock (a8d031)!
Installing dependencies from Pipfile.lock (a8d031)...
🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 83/83 — 00:02:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
All dependencies are now up-to-date!
```
There are still some outstanding package safety warnings after the update.
```zsh
@roger2hk ➜ /workspaces/trillian-examples/witness/ethereum (master ✗) $ …
```

Bump multiple pip dependencies in witness/ethereum

---

go.mod
serverless/deploy/github/distributor/combine_witness_signatures/go.mod
serverless/deploy/github/log/sequence_and_integrate/go.mod
serverless/experimental/gcp-log/gcs_uploader/go.mod
serverless/experimental/gcp-log/gcs_uploader/go.sum

This is what trillian is using now. It seems unlikely someone would need higher levels of backwards compatibility in the examples repo.
`go mod tidy` caused a lot of changes.
https://go.dev/doc/modules/gomod-ref notes that `The go.mod file
includes an explicit require directive for each module that provides any
package transitively imported by a package or test in the main module`
which changed with 1.17.

Updated all go versions to minimum of 1.17

---

integration/Dockerfile

See https://github.com/google/trillian/pull/2791

Make trillian-examples lint version consistent with trillian

---

witness/golang/omniwitness/distributor_configs/witness.yaml
witness/golang/omniwitness/feeder_configs/pixel.yaml
witness/golang/omniwitness/witness_configs/witness.yaml

The Pixel log key appears to have changed its name, update witness configs to match.

Update Pixel log signing ID name

---

feeder/cmd/rekor_feeder/example_config.yaml
internal/feeder/rekor/rekor_feeder.go
witness/golang/omniwitness/distributor_configs/witness.yaml
witness/golang/omniwitness/feeder_configs/rekor.yaml
witness/golang/omniwitness/witness_configs/witness.yaml

This updates the feeder to specify the shard ID when fetching a consistency proof, using the ID from the config.
I also needed to update fetching the latest checkpoint, searching for the checkpoint that matches the shard ID from the config.
Also added the new shard to the configs, and updated the Origin to match what's now returned by Rekor.
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

Fix Rekor feeder to handle sharded logs

---

.github/dependabot.yml

Configure dependabot to update github actions, too.

Dependabot for GH actions too

---

.github/workflows/codeql-analysis.yml
.github/workflows/link_checker.yaml

Pin our GitHub Action configs to explicit git hashes.
This reduces the potential for compromised dependencies to undermine our own repo security.

Pin GitHub actions to git hashes

---

cloudbuild.yaml
cloudbuild_docker.yaml

The default behavior in Go 1.16 is `GO111MODULE=on`. It is safe to remove this environment variable as this repo is using Go 1.19.

Remove GOMODULE111 in cloudbuild scripts

---

internal/feeder/rekor/rekor_feeder.go
serverless/config/log.go
serverless/config/log_test.go
witness/golang/omniwitness/distributor_configs/witness.yaml
witness/golang/omniwitness/feeder_configs/rekor.yaml
witness/golang/omniwitness/witness_configs/witness.yaml

This PR moves the configuration of the Rekor `treeID` into the `LogURL` field rather than overloading `ID`.
The URL is a more natural place for this param (indeed, `treeID` ends up as a HTTP param on the request), and overriding `ID` has the unfortunate side effect of changing the directory name for the log in current distributor implementations away from the default derived hash value to a value which all distributor clients would need to configure.

[Witness/Feeder] Configure Rekor treeID via URL

---

serverless/cmd/client/client.go

This adds a command-line argument to the client command-line tool that allows the entry to be looked up by Merkle leaf hash instead of by a file containing the entry itself.
Note that the hash here is the RFC6962 leaf hash and not just the SHA256 hash of the leaf's contents. The hashed data is a single 0 byte followed by the leaf's contents.

Allow inclusion proofs to be looked up by leaf hash.

---

clone/cmd/serverlessclone/serverlessclone.go
serverless/client/client.go
serverless/client/witness/consensus.go
serverless/client/witness/consensus_test.go
serverless/experimental/wasm/main.go
serverless/integration/integration_test.go

This updates the transparency log checkpoint tracker to make the checkpoint's signature(s) available for client code that wants to verify the signature itself.

Make checkpoint signatures available from checkpoint tracker.

---

README.md
witness/README.md
witness/golang/README.md
witness/golang/omniwitness/README.md
witness/golang/omniwitness/internal/omniwitness/omniwitness.go
witness/golang/omniwitness/monolith/README.md

The monolith should be the default witness that most people should find themselves at; it is simple to deploy and follows all known logs. The other configurations (dockerized, bare witness) are still useful, but only to advanced users that know they don't want the monolith.

Made the monolith easier to discover, and better documented

---

witness/golang/omniwitness/monolith/Dockerfile

This is consistent with the Dockerfiles of the subcomponents, and removes the omniwitness from being the only target in `cloudbuild_docker.yaml` that uses a non-alpine release base. This may resolve #717. In addition, it should make the release image a lot smaller.

Use alpine instead of buster for the release image of omniwitness monolith

---

go.mod
go.sum
serverless/deploy/github/distributor/combine_witness_signatures/go.mod
serverless/deploy/github/distributor/combine_witness_signatures/go.sum

All distributors and witnesses will need to redeploy in order to re-sync on IDs

Breaking change: use new ID function for logs

---

witness/golang/cmd/witness/impl/witness.go

This currently fails because of the colliding Rekor configs. This PR should not be merged until https://github.com/transparency-dev/formats/issues/14 is addressed and the dependency here is updated.

Witness bails with error if config has log configs with duplicate IDs

---

internal/distribute/github/distribute.go

There are logs that share a signing key, and the old behaviour caused collisions in branch names. The new version is less readable, but more correct.

Use log ID instead of log name in distributor branches

---

serverless/deploy/github/distributor/README.md

The distributor_pr action no longer needs the full history of the repo, so only check out the last commit. This can speed the action up quite a bit.

[Serverless/witness] Update example actions config

---

integration/Dockerfile

This incorporates the fix for the missing compatibility signal symbol to unblock #756

Bump tamago to 1.20.2

---

distributor/cmd/internal/distributor/distributor.go
distributor/cmd/internal/distributor/distributor_test.go

This will allow the HTTP server to return appropriate error codes for these mose obvious cases

Return error codes for user-triggered errors

---

distributor/cmd/internal/distributor/distributor.go
distributor/cmd/internal/distributor/distributor_test.go

`INSERT OR REPLACE INTO` doesn't work in MariaDB. Fortunately, we already knew in the code where this was a first-time insert or an update, so the SQL has been simplified to something that works with both MariaDB and sqlite.

Use SQL syntax that works in MariaDB

---

scripts/presubmit.sh

This is neater now, and avoids combinatorial growth should other optional flags be needed by the test invocation

Unify the coverage and non-coverage test invocation

---

.github/dependabot.yml
binary_transparency/firmware/cmd/ft_personality/Dockerfile
binary_transparency/firmware/cmd/ftmapserver/Dockerfile
clone/cmd/ctclone/Dockerfile
clone/cmd/ctverify/Dockerfile
clone/cmd/sumdbclone/Dockerfile
feeder/cmd/pixel_bt_feeder/Dockerfile
feeder/cmd/rekor_feeder/Dockerfile
feeder/cmd/sumdb_feeder/Dockerfile
serverless/cmd/distribute/github/Dockerfile
serverless/cmd/feeder/Dockerfile
serverless/deploy/github/distributor/combine_witness_signatures/Dockerfile
serverless/deploy/github/distributor/update_logs_index/Dockerfile
serverless/deploy/github/log/leaf_validator/Dockerfile
serverless/deploy/github/log/sequence_and_integrate/Dockerfile
sumdbaudit/docker/mirror/Dockerfile
sumdbaudit/docker/witness/Dockerfile
witness/golang/cmd/omniwitness/Dockerfile
witness/golang/cmd/witness/Dockerfile

This is motivated by #788. Using explict tags that are updated by dependabot seems like the pragmatic solution to this problem.
- Explicit alpine image usage
- Update golang:buster images to latest explicit version
- Update golang:1.19-alpine images to latest explicit version

Explicit version tags for docker images

---

distributor/cmd/internal/distributor/distributor.go
distributor/cmd/internal/distributor/distributor_test.go

The exact threshold of the max N should probably be configurable eventually, but having some max is better than nothing to prevent easy queries of death.

Distributor explicitly handles zero and large numbers

---

distributor/cmd/internal/distributor/distributor_test.go

glog.Fatalf causes the useful information to be lost in a stack trace of all threads. This approach is much more concise and still outputs the last error logged.

Fail more gracefully if docker not detected

---

helloworld/README.md

The docker-compose file uses "-" in the container name, adjusting the docs to make it easier for a anyone to run the tool.
Thans guys, 
You are amazing <3

docs: fix docker-compose container name mismatch

---

distributor/cmd/main.go
distributor/docker-compose.yaml

The witnesses that a distributor accepts should not be statically compiled into the code as we don't have a strong opinion on this set. The logs could also be made configurable at runtime in the future, but for now keeping these the same as the omniwitness makes configuration simpler and doesn't alienate any users.
Also updated ports to avoid collisions with witness.

Allow witnesses to be configured at runtime

---

distributor/cmd/logs.yaml
go.mod
go.sum
serverless/cmd/client/client.go
serverless/config/log.go

This is a breaking change that will cause all of the log IDs to be different than they were before.
Also updated the Pixel BT log origin. May as well put all the breaking changes together!

Breaking: Update to latest version of td-formats

---

distributor/cmd/internal/distributor/distributor_test.go

This is a missing feature at the moment; the current behaviour of
getCheckpointN looks at the latest checkpoints for each witness and
merges them. This doesn't catch the case where witnesses are not aligned
at the point where the getCheckpointN is called.

Added test for getting checkpoint that has been available

---

serverless/deploy/github/distributor/README.md

Closes #838 
Update `serverless/deploy/github/distributor/README.md` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the example config that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' -o -name '*.md' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
echo "::set-output name=pr::$(cat NR)"
```
**TO-BE**
```yaml
echo "pr=$(cat NR)" >> $GITHUB_OUTPUT
```

Replace deprecated command with environment file

---

clone/internal/verify/verify.go
clone/logdb/database.go
clone/logdb/database_test.go

This is a long-running operation and now respects context cancellation.
Also changed the two returns channels to combine them into a single channel. This is far easier to understand and implement bug-free code with. Previously the err channel wasn't closed, which wasn't clean. Now everything is closed when StreamLeaves returns.

Improve the StreamLeaves API and implementation

---

serverless/cmd/client/client.go

Use `strconv`'s ["figure it out" functionality](https://pkg.go.dev/strconv#ParseInt) to auto-detect the correct base for the int flag arguments.

Autodetect int argument representations

---

clone/logdb/database.go
serverless/cmd/clone2serverless/README.md
serverless/cmd/clone2serverless/main.go
serverless/cmd/integrate/main.go
serverless/experimental/wasm/main.go
serverless/integration/integration_test.go
serverless/pkg/log/integrate.go

This tool allows a file-based mirror of any cloneable log to be created. This required a change to Integrate to remove the requirement for a prior checkpoint. This has been replaced with the fromSize. In the case of mirrors, we can't create and sign a valid checkpooint of size 0, which is what the integrate command had assumed was possible from its previous usage.
TODO: write up instructions for setting up a filesystem that can handle this without running out of space / inodes.

Added tool for creating tile-based logs from cloned log

---

binary_transparency/firmware/cmd/ftmapserver/impl/ftmapserver.go
binary_transparency/firmware/internal/crypto/signature.go

Fixes https://github.com/google/trillian-examples/security/code-scanning/5, https://github.com/google/trillian-examples/security/code-scanning/7, https://github.com/google/trillian-examples/security/code-scanning/8.

Added size checks on unsafe operations

---

.github/dependabot.yml

Made it internally consistent by removing quotes, and making everything daily. Removed the limit for open PRs as we haven't used that, and the other ecosystem stanzas don't have it. Removed the docker stanza for the root as there is no Dockerfile there.

Clean up dependabot config

---

go.mod
serverless/deploy/github/distributor/combine_witness_signatures/go.mod
serverless/deploy/github/distributor/update_logs_index/go.mod
serverless/experimental/gcp-log/gcs_uploader/go.mod

We support the last two minor versions (1.20 and 1.21).

Bump Go from 1.19 to 1.20

---

go.mod
go.sum

Fixes https://github.com/google/trillian-examples/security/dependabot/46.

Bump github.com/u-root/u-root from 7.0.0+incompatible to 0.11.0

---

clone/README.md
clone/cmd/ctclone/ctclone.go
clone/cmd/serverlessclone/serverlessclone.go
clone/cmd/sumdbclone/sumdbclone.go
clone/internal/cloner/clone.go
clone/internal/cloner/clone_test.go

Previously each clone tool implementation was responsible for calling Clone() and then Verify() and then persisting the checkpoint to the database. A bad implementation could have written the checkpoint with incomplete verification, which would have broken the expected contract for these tools.
This change makes this contract about when leaves can be trusted far clearer. The API makes this hard to get wrong, and the docs have been updated to clearly communicate what can be expected of the data. The docs also make it clearer that this is expected to be the first stage of a pipeline, and that the leaf data being raw isn't a blocker because later pipeline stages can parse this.

Tighter clone semantics for DB writing

---

clone/cmd/ctclone/ctclone.go
clone/cmd/ctclone/ctclone_test.go
clone/cmd/serverlessclone/serverlessclone.go
clone/cmd/sumdbclone/sumdbclone.go
clone/internal/cloner/clone_test.go
clone/internal/download/batch.go
clone/internal/download/batch_test.go

Adapt ctclone to handle the 'coerced get-entries' feature by: trying to retrieve just one request, checking the number of returned results, either continuing with the rest workers, or stopping fetching, storing the incomplete tile, exiting delegating orchestration system to start the process again.
Fixes https://github.com/google/trillian-examples/issues/1044

Adapt ctclone for 'coerced get-entries' in Let's Encrypt and other CT Logs

---

binary_transparency/firmware/internal/client/client.go

A redirect on a POST request will make the http client perform a GET request to the signposted URL. This will (probably) return a 200, which the code will then interpret as a successful POST. This check ensures that the method the response relates to is the same as the one we invoked.

Safeguard against redirects on POST request

---

integration/Dockerfile

This PR fixes the broken cloud build pipeline to unblock Dependabot PRs.

Update Debian apt source from `buster-backports` to `bullseye-backports`

---

.github/dependabot.yml

Security updates will still come through separately

Group dependabot updates together

---

go.mod
go.sum

This avoids CVE-2024-41110. Updating to any newer version of this dep causes compilation errors due to moved declarations which are used from beam packages.

Bump docker

---

.github/dependabot.yml

This will also make it so that dependabot will update all of these grouped dependencies in a single PR. See https://github.com/google/trillian/pull/3672 for the first application of this in the trillian repo. This will massively cut down on maintenance costs and make PR history much easier to digest.

[Dependabot] Use multi-directory to reduce duplicate config

---

.github/dependabot.yml

The github distributor was deleted, but these configs still remained.

[Dependabot] Remove deleted files from config
