google/trillian-examples

- .gitignore
> Pull in some more gitignore from trillian repo

- etherslurp/cmd/follower/main.go
- etherslurp/cmd/mapper/main.go
- etherslurp/cmd/ui/main.go
- etherslurp/follower/follower.go
- etherslurp/mapper/mapper.go
- etherslurp/ui/ui.go
A bunch of fixes for metalint issues.
> metalint fixes

- etherslurp/Makefile
- etherslurp/README.md
> Add geth cleanup target and fix datadir

- .gometalinter.json
- .travis.yml
- etherslurp/mapper/mapper.go
- etherslurp/ui/ui.go
- scripts/check_unforked.sh
- scripts/presubmit.sh
Fix a couple of problems and make the builds more similar to the main Trillian repo.
> Improve builds

- gossip/api/types.go
- gossip/api/types_test.go
- gossip/client/hubclient.go
- gossip/client/hubclient_test.go
This is kind of big, so I'm not expecting to get the whole chain of commits reviewed in one go - maybe start with the first couple of commits and touch base after that?
> Gossip Hub implementation

- gossip/integration/hubenv.go
- gossip/integration/integration.go
- gossip/integration/integration_test.go
Add a simple integration test that logs signed blobs and checks
all of the API entrypoints for the Gossip Hub.
> gossip: add in-process integration test

- .gitignore
- .travis.yml
- gossip/hub/hub_server/main.go
- gossip/integration/gossip_functions.sh
- gossip/integration/gossip_killall.sh
- gossip/integration/gossip_test.sh
- gossip/integration/integration.go
- gossip/integration/integration_test.go
- gossip/integration/make_hub_cfg/main.go
- gossip/integration/prometheus.yml
Mostly borrowing the structure of the CTFE out-of-process integration tests, but with an extra utility to generate config files (with real, per-test keys in them).
> Out-of-process gossip integration test

- gossip/testdata/to_proto/main.go
Allow other PEM blocks (e.g. "EC PARAMETERS") to appear and still
transmute the key.
> gossip: make to_proto tool more robust

- etherslurp/Makefile
Fixes #22, switches tlsigner's rpc port to 8093
> Changes rpc port for tlsigner

- gossip/hub/handlers.go
- gossip/hub/handlers_test.go
- gossip/hub/hub_server/main.go
- gossip/hub/instance.go
Easiest to review commit-by-commit:
- export handler Name
- per-user quota support
> Tweaks to Gossip hub

- gossip/scanner/fetcher.go
Closely based on github.com/google/certificate-transparency-go/scanner
> gossip: add scanner package

- gossip/hub/instance_test.go
> Fix a couple of unhandled errors in gossip example test

- gossip/hub/instance_test.go
> Fix config protos in trillian-examples Gossip

- registers/Makefile
> Fix port clash in registers example

- binary_transparency/firmware/cmd/ft_monitor/main.go
- go.mod
- go.sum
- registers/records/records.go
Fix lint and golang 1.15 issues.
> Fix lint issues

- binary_transparency/firmware/cmd/ft_monitor/main.go
Monitor has been modified to add support for Image verification
> Monitor support for Image Verification

- binary_transparency/firmware/README.md
Some doc tweak suggestions from Simon.
> Demo README tweaks

- binary_transparency/firmware/README.md
- binary_transparency/firmware/devices/dummy/rom/rom.go
Updated README to reflect the correct status.
Updated rom verification on code boot to include signature verification logic.
> Update README and add emu ROM signature changes

- binary_transparency/firmware/cmd/usb_armory/image_builder/build.sh
- binary_transparency/firmware/devices/usb_armory/README.md
- binary_transparency/firmware/devices/usb_armory/bootloader/Makefile
- binary_transparency/firmware/devices/usb_armory/bootloader/boot.go
- binary_transparency/firmware/devices/usb_armory/bootloader/ext4.go
- binary_transparency/firmware/devices/usb_armory/bootloader/ft.go
- binary_transparency/firmware/devices/usb_armory/bootloader/main.go
- go.mod
- go.sum
- Define the firmware measurement strategy
- Add script to help build valid firmware images
- Update docs
> Flesh out armory transparency story

- experimental/batchmap/sumdb/build/map.go
Running at -v=1 now allows for readable output, where setting -v=2 will drown you in all of the pipeline schedule output. This stuff can be useful when debugging the pipeline but is bonkers for a demo.
> Redirect logs to glog and reduce verbosity

- binary_transparency/firmware/cmd/flash_tool/flash_tool.go
- binary_transparency/firmware/internal/verify/bundle.go
- binary_transparency/firmware/internal/verify/bundle_test.go
> Add consistency and signature verification for bundle

- sumdbaudit/README.md
These instructions were tested on a Raspberry Pi. They should work for any Linux distro that uses systemd.
> Added docs for setting up mirror as a service

- sumdbaudit/README.md
- sumdbaudit/docker/docker-compose.yml
- sumdbaudit/docker/mirror/Dockerfile
- sumdbaudit/docker/witness/Dockerfile
Docker Compose script brings them both up and makes them work together. Witness will be serving at :8080.
> Added dockerfiles for mirror and witness

- CONTRIBUTORS
- binary_transparency/firmware/README.md
Add --device=dummy to flash_tool
> Update FT README.md

- sumdbaudit/README.md
- sumdbaudit/docker/docker-compose.rpi.yml
- sumdbaudit/docker/docker-compose.yml
> Include docker-compose for RPi

- binary_transparency/firmware/api/witness.go
- binary_transparency/firmware/cmd/ft_witness/ft_witness.go
- binary_transparency/firmware/cmd/ft_witness/impl/ft_witness.go
- binary_transparency/firmware/cmd/ft_witness/internal/http/server.go
- binary_transparency/firmware/cmd/ft_witness/internal/http/witness.go
- binary_transparency/firmware/cmd/ft_witness/internal/http/witness_test.go
- binary_transparency/firmware/cmd/ft_witness/internal/ws/store.go
- binary_transparency/firmware/cmd/ft_witness/internal/ws/store_test.go
[WIP] FT Witness work in progress.
> First revision of interim FT Witness changes

- serverless/integration/integration_test.go
- serverless/internal/client/client.go
- Adds client-side proof building code
- First cut of integration test
> [serverless] Client proof builder & integration test

- serverless/cmd/client/client.go
- serverless/integration/integration_test.go
- serverless/internal/client/client.go
Adds support to client for using the `leafhash`->`sequence` index.
> [serverless] Add client support for index lookup

- serverless/README.md
Add some usage examples for the CLI tools.
> [serverless] Add some usage docs for CLI tools

- binary_transparency/firmware/cmd/flash_tool/impl/flash_tool.go
- binary_transparency/firmware/internal/client/mapclient.go
These commits failed to get pushed into #304 before I merged.
> Simpler JSON unmarshalling

- serverless/deploy/github/README.md
- serverless/deploy/github/leaf_validator/Dockerfile
- serverless/deploy/github/leaf_validator/action.yaml
- serverless/deploy/github/leaf_validator/entrypoint.sh
- serverless/deploy/github/sequence_and_integrate/action.yaml
This adds a simple leaf PR validator GitHub Action to the serverless example.
Example repo https://github.com/AlCutter/serverless-test
> [Serverless] Add example leaf validator action

- binary_transparency/firmware/internal/crypto/key_info.go
- binary_transparency/firmware/internal/crypto/signature.go
In prep for migrating to checkpoint format in `/formats/log`
> [Firmware] Add test keys for checkpoint signing

- binary_transparency/firmware/docs/design/README.md
Thanks to Yogesh for spotting these.
> Fix hyperlinks

- serverless/README.md
- serverless/cmd/client/client.go
- serverless/cmd/integrate/main.go
- serverless/cmd/sequence/main.go
- serverless/integration/integration_test.go
- serverless/internal/client/client.go
Initial commit for feedback.
TODO:
[ ] update readme
[ ] update Client
> [serverless] Checkpoint signing

- serverless/deploy/github/sequence_and_integrate/entrypoint.sh
- serverless/deploy/github/sequence_and_integrate/go.mod
- serverless/deploy/github/sequence_and_integrate/go.sum
- check for existence of `checkpoint` and init if not there
- update action mod to point to latest version of serverless (to pick up signing support)
> [Serverless] Have action attempt to initialise empty log

- clone/README.md
- clone/cmd/ctverify/Dockerfile
- clone/cmd/ctverify/ctverify.go
- clone/internal/logdb/database.go
- clone/internal/logdb/database_test.go
- clone/internal/verify/verify.go
- clone/internal/verify/verify_test.go
This is based on top of #338, and verifies the leaves downloaded by that tool.
> Tool & library to verify local data integrity against checkpoint

- serverless/README.md
- serverless/deploy/github/README.md
- Mark TODOs as done
- Remove a couple of TODOs which don't really need doing.
- Add link to GitHub Actions docs & configs
> [serverless] Update README

- serverless/internal/layout/README.md
- Checkpoint (not state)
- Tile file serialisation
> [serverless] Update layout docs

- serverless/client/client.go
Also tidied some formatting / error messages for consistency.
> Added client method to get leaf preimage at an index

- witness/golang/api/http.go
- witness/golang/cmd/witness/example.conf
- witness/golang/cmd/witness/internal/http/server.go
- witness/golang/cmd/witness/internal/witness/witness.go
- Fix handler registrations
- Return 404 rather than 500 if we don't have a checkpoint for a known log
- Consider an update to an equivalent checkpoint "ok" (but don't do any work) to smoother over races.
> [Witness] Few small fixes

- witness/golang/cmd/witness/main.go
Fix flag name for secret key, and remove test private key.
> [witness] fix sk flag

- formats/checkpoints/combine_signatures.go
- formats/checkpoints/combine_signatures_test.go
- serverless/cmd/feeder/feed-to-github
This PR adds a companion tool to the witness PR handler action in #396 .
> [Serverless] Add one-shot witness PR creation tool

- README.md
- witness/README.md
- witness/golang/README.md
I also deleted the mention of tritter in the main readme because we discussed deleting that example so I will do so in a future PR.
> adding witness readmes, changing the main one

- scripts/presubmit.sh
- serverless/deploy/github/sequence_and_integrate/go.sum
- Add missing deps
- Add test to presubmit script to build Docker images.
> Serverless fix actions

- serverless/cmd/feeder/feed-to-github
- serverless/deploy/github/witness_pr/README.md
Fixes one-char typos in `TRILLIAN_WORSPACE` and `privilesges`.
> Fix typos.

- serverless/experimental/wasm/wasm_exec.js
Companion to #414, just to save folks having to copy it in themselves.
No need to review, the code itself, it's just the vanilla `$(go env GOROOT)/misc/wasm/wasm_exec.js` file.
> [serverless] Add Go wasm shim

- serverless/experimental/wasm/README.md
- serverless/experimental/wasm/main.go
Updated readme as there was a path wrong.
> Allow the checkpoint file to be missing first time

- witness/golang/cmd/witness/internal/witness/witness_test.go
Also fixed up one test that included something which failed signature checks before the size was looked at.
> Regenerate the log keypair and include SK for maintainability

- clone/cmd/ctclone/ctclone.go
This was using a lock-free mechanism before, which worked but isn't a good practice.
This change was initially created to avoid seeing > 100% work in any reporting window. It seems to reduce that but not completely avoid it. The reason for that is that work isn't cleanly divided into reporting chunks and can overlap reporting periods, but only be counted in one of them.
> Use locking in reporter to avoid anomolies

- serverless/cmd/feeder/github/main.go
- Update location to store witnessed checkpoints
Part of #457
> [Serverless] Fix up feeder

- serverless/cmd/feeder/github/main.go
- serverless/deploy/docker/witness/README.md
- serverless/deploy/docker/witness/docker-compose.yaml
Paired with #467 and part of #464
> [Serverless] Update feeder to support distributor

- serverless/cmd/feeder/github/main.go
Makes the GitHub feeder be a little less eager to raise distributor PRs.
> [Serverless] Don't spam distributor when there's nothing to do

- serverless/deploy/github/distributor/combine_witness_signatures/combine_witness_signatures.go
Should fail hard and cause GitHub Actions to error our if there are any problems with the input.
> [serverless/distro] Fail hard if problems are found

- serverless/deploy/github/distributor/README.md
- serverless/deploy/github/distributor/combine_witness_signatures/example_config.yaml
> Updated distributor docs to refer to yaml instead of json

- serverless/deploy/github/distributor/README.md
- serverless/deploy/github/distributor/combine_witness_signatures/README.md
- serverless/deploy/github/log/README.md
This is a really easy thing to overlook and is annoying to debug because nothing happens on PR proposal and there is nowhere to look for diagnostics about why actions aren't firing
> Added comment about branch naming to configs

- serverless/cmd/feeder/impl/feeder.go
This cleans up after changing from many witnesses to one, and avoids the need to fetch the checkpoint again after Update succeeds.
> Tidied up the feeder

- serverless/cmd/feeder/github/main.go
- serverless/internal/git/git.go
- serverless/internal/github/github.go
The goal is to make this code reusable, and also improve legibility of the main files. Ideally this will also lead to the ability to test this stuff with a fake git repository.
> Encapsulated git repo stuff into its own class

- serverless/deploy/github/distributor/README.md
- serverless/deploy/github/log/README.md
Add example config and docs for enabling automatic merging of distributor PRs. This removes a lot of the friction here, and will help ensure that witnessed checkpoints are relatively fresh.
_Background [music for reviewing](https://www.youtube.com/watch?v=L7NAURuXW8c)_
> [serverless] Add automerge docs/example for distributor

- serverless/cmd/distribute/github/main.go
This should help keep the number of branches pushed to the distributor forks down, since they'll get reused for each subsequent checkpoint.
> [serverless/distro] Use fixed branch name per {witness,log} pair

- internal/feeder/feeder.go
- internal/feeder/feeder_test.go
- serverless/cmd/feeder/main.go
- sumdbaudit/witness/cmd/feeder/main.go
- sumdbaudit/witness/cmd/feeder/main_test.go
The intention is to try to share some of the error handling for corner cases across feeders.
Probably worth reviewing commit by commit.
> [Feeder] Factor out some common code

- feeder/cmd/rekor_feeder/example_config.yaml
- feeder/cmd/rekor_feeder/main.go
- serverless/config/log.go
This builds upon #539 to provide a Sigstore/Rekór feeder.
> Add a SigStore/Rekór feeder

- serverless/cmd/distribute/github/main.go
> Add support for Sigstore logs to distributor

- cloudbuild_docker.yaml
- feeder/cmd/rekor_feeder/Dockerfile
- feeder/cmd/rekor_feeder/README.md
- scripts/presubmit.sh
> Add Dockerfile for Sigstore feeder

- feeder/cmd/pixel_bt_feeder/standalone.conf/pixelwitness.yaml
- sumdbaudit/witness/witness.yaml
- witness/golang/cmd/witness/example_config.yaml
- witness/golang/cmd/witness/impl/witness.go
This is consistent with the other configuration files in this repository. This is a breaking change for any existing witnesses, who will need to update the configuration files once updating to a build that has this change.
> Rename PubKey/PubKeyType to PublicKey*

- serverless/README.md
Looks like the docs and code had drifted out of alignment.
> [serverless] Fix up main README

- go.mod
- go.sum
- serverless/client/client.go
Updated internals for change from int64 to uint64.
> Use latest version of merkle library

- witness/golang/omniwitness/usbarmory/main.go
- witness/golang/omniwitness/usbarmory/storage/internal.go
> [Witness/Armory] Add support for reading/writing blocks to SD/MMC

- internal/distribute/github/distribute.go
Previously we were creating the filename based on the unsigned checkpoint body, which meant that there would be a collision when two different witnesses attempted to distribute the same checkpoint. Using the raw checkpoint means that this collision will be avoided, which should allow for better throughput, latencyand, and scaling for distributing checkpoints for the same log when there are multiple witnesses.
> Distributor incoming files have unique names

- cloudbuild_docker.yaml
Also add quotes to docker step for style consistency.
> Switch cloudbuild_docker.yaml newline from folded to literal style.

- cloudbuild_docker.yaml
I have deployed the GCF functions to the CI project. I tested calling the functions from Cloud Build on my project.
> Add GCF call steps to cloudbuild_docker.yaml

- cloudbuild_docker.yaml
Also re-order `waitFor` and `id` to be consistent with the rest of the file.
> Add id for CloudBuild step.

- witness/golang/omniwitness/docker-compose.yaml
This was removed from the binary in #625
> Remove broken flag from omniwitness docker-compose

- serverless/experimental/gcp-log/internal/storage/storage.go
If it already exists, try the next number.
See documentation:
* https://cloud.google.com/storage/docs/object-versioning
* https://cloud.google.com/storage/docs/metadata#generation-number
* https://cloud.google.com/storage/docs/request-preconditions#special-case
> Conditionally write sequence number. 

- feeder/cmd/rekor_feeder/example_config.yaml
Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>
> Fix example config for rekor feeder

- internal/feeder/feeder.go
Also fixed comment that got weirdly eaten in the past
> Improve logging to make it clearer in rekor case where they reuse signing key

- serverless/deploy/github/distributor/README.md
Addresses the `node12` and `set-output` warnings.
> [Serverless/witness] Update example actions config

- helloworld/README.md
- helloworld/docker-compose.yaml
For people with a docker environment already set up, this is cleaner.
> Docker compose for hello world

- distributor/cmd/internal/distributor/distributor_test.go
- distributor/docker-compose.yaml
- sumdbaudit/docker/docker-compose.yml
There is a remaining use of MYSQL_IP in experimental/batchmap/ctmap/README.md but this would need more testing before changing
> Replace missed MYSQL_ vars from #834

- serverless/internal/storage/fs/fs.go
- serverless/internal/storage/fs/fs_test.go
- serverless/pkg/log/integrate.go
This is useful if creating a mirroring/clone tool.
> Provide function for assigning directly to a given sequence number

- serverless/deploy/github/distributor/combine_witness_signatures/go.mod
- serverless/deploy/github/distributor/combine_witness_signatures/go.sum
- serverless/deploy/github/distributor/update_logs_index/go.mod
- serverless/deploy/github/distributor/update_logs_index/go.sum
This saves 4 dependabot workflows
> Manually updated deps for 2 submodules

- experimental/batchmap/sumdb/build/pipeline/pipeline_test.go
- go.mod
- go.sum
Local equivalent to google/trillian#3083.
> Register BEAM DoFns

- experimental/batchmap/sumdb/build/pipeline/log.go
> Add another missing DoFn registration

- clone/cmd/sumdbverify/Dockerfile
- clone/cmd/sumdbverify/verify.go
- clone/cmd/sumdbverify/verify_test.go
This checks all of the cloned entries from the sumdb log and checks for any entries with the same module and version, but different hashes.
> Added verifier for sumdb claims

- clone/cmd/sumdbclone/internal/client/sumdb.go
- clone/cmd/sumdbclone/internal/client/sumdb_test.go
- go.mod
> Fix extra spaces on last leaf in bundle

- CONTRIBUTORS
- clone/logdb/database.go
> Clone tool: use max size uint in DB schema

- experimental/vindex/README.md
- experimental/vindex/map.go
- experimental/vindex/map_test.go
This is a shared place for those of us that have been discussing these
ideas to collaborate and nudge things forward in between main projects.
> Verifiable Index skeleton
